import type { Metadata } from "next";
import DialogProvider from "ui/Dialog/DialogProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body>
      <DialogProvider>
        {children}</DialogProvider></body>
    </html>
  );
}
