import theme from '../theme.css';
import type { ButtonColorThemeWithStatus, ButtonSizeTheme } from './types';

export const bgColors: Record<ButtonColorThemeWithStatus, string> = {
  'fill-primary-default': theme.colors.white,
  'fill-secondary-default': theme.colors.gray700,
  'fill-success-default': theme.colors.success,
  'fill-danger-default': theme.colors.error,
  'fill-primary-hover': theme.colors.gray50,
  'fill-secondary-hover': theme.colors.gray600,
  'fill-success-hover': theme.colors.blue500,
  'fill-danger-hover': theme.colors.red500,
  'fill-primary-press': theme.colors.gray100,
  'fill-secondary-press': theme.colors.gray500,
  'fill-success-press': theme.colors.blue600,
  'fill-danger-press': theme.colors.red600,
  'outlined-primary-default': 'transparent',
  'outlined-secondary-default': 'transparent',
  'outlined-success-default': 'transparent',
  'outlined-danger-default': 'transparent',
  'outlined-primary-hover': 'transparent',
  'outlined-secondary-hover': 'transparent',
  'outlined-success-hover': theme.colors.blueAlpha100,
  'outlined-danger-hover': theme.colors.redAlpha100,
  'outlined-primary-press': 'transparent',
  'outlined-secondary-press': 'transparent',
  'outlined-success-press': theme.colors.blueAlpha100,
  'outlined-danger-press': theme.colors.redAlpha100,
  'text-primary-default': 'transparent',
  'text-secondary-default': 'transparent',
  'text-success-default': 'transparent',
  'text-danger-default': 'transparent',
  'text-primary-hover': 'transparent',
  'text-secondary-hover': 'transparent',
  'text-success-hover': 'transparent',
  'text-danger-hover': 'transparent',
  'text-primary-press': 'transparent',
  'text-secondary-press': 'transparent',
  'text-success-press': 'transparent',
  'text-danger-press': 'transparent',
  'floating-primary-default': theme.colors.white,
  'floating-secondary-default': theme.colors.gray700,
  'floating-success-default': theme.colors.success,
  'floating-danger-default': theme.colors.error,
  'floating-primary-hover': theme.colors.gray50,
  'floating-secondary-hover': theme.colors.gray600,
  'floating-success-hover': theme.colors.blue500,
  'floating-danger-hover': theme.colors.red500,
  'floating-primary-press': theme.colors.gray100,
  'floating-secondary-press': theme.colors.gray500,
  'floating-success-press': theme.colors.blue600,
  'floating-danger-press': theme.colors.red600,
};

export const textColors: Record<ButtonColorThemeWithStatus, string> = {
  'fill-primary-default': theme.colors.gray800,
  'fill-secondary-default': theme.colors.white,
  'fill-success-default': theme.colors.white,
  'fill-danger-default': theme.colors.white,
  'fill-primary-hover': theme.colors.gray800,
  'fill-secondary-hover': theme.colors.white,
  'fill-success-hover': theme.colors.white,
  'fill-danger-hover': theme.colors.white,
  'fill-primary-press': theme.colors.gray800,
  'fill-secondary-press': theme.colors.white,
  'fill-success-press': theme.colors.white,
  'fill-danger-press': theme.colors.white,
  'outlined-primary-default': theme.colors.white,
  'outlined-secondary-default': theme.colors.white,
  'outlined-success-default': theme.colors.success,
  'outlined-danger-default': theme.colors.error,
  'outlined-primary-hover': theme.colors.white,
  'outlined-secondary-hover': theme.colors.white,
  'outlined-success-hover': theme.colors.blue500,
  'outlined-danger-hover': theme.colors.red500,
  'outlined-primary-press': theme.colors.white,
  'outlined-secondary-press': theme.colors.white,
  'outlined-success-press': theme.colors.blue600,
  'outlined-danger-press': theme.colors.red600,
  'text-primary-default': theme.colors.gray30,
  'text-secondary-default': theme.colors.gray30,
  'text-success-default': theme.colors.gray30,
  'text-danger-default': theme.colors.gray30,
  'text-primary-hover': theme.colors.gray50,
  'text-secondary-hover': theme.colors.gray50,
  'text-success-hover': theme.colors.gray50,
  'text-danger-hover': theme.colors.gray50,
  'text-primary-press': theme.colors.gray100,
  'text-secondary-press': theme.colors.gray100,
  'text-success-press': theme.colors.gray100,
  'text-danger-press': theme.colors.gray100,
  'floating-primary-default': theme.colors.black,
  'floating-secondary-default': theme.colors.white,
  'floating-success-default': theme.colors.white,
  'floating-danger-default': theme.colors.white,
  'floating-primary-hover': theme.colors.black,
  'floating-secondary-hover': theme.colors.white,
  'floating-success-hover': theme.colors.white,
  'floating-danger-hover': theme.colors.white,
  'floating-primary-press': theme.colors.black,
  'floating-secondary-press': theme.colors.white,
  'floating-success-press': theme.colors.white,
  'floating-danger-press': theme.colors.white,
};

export const borders: Record<ButtonColorThemeWithStatus, string> = {
  'fill-primary-default': 'none',
  'fill-secondary-default': 'none',
  'fill-success-default': 'none',
  'fill-danger-default': 'none',
  'fill-primary-hover': 'none',
  'fill-secondary-hover': 'none',
  'fill-success-hover': 'none',
  'fill-danger-hover': 'none',
  'fill-primary-press': 'none',
  'fill-secondary-press': 'none',
  'fill-success-press': 'none',
  'fill-danger-press': 'none',
  'outlined-primary-default': `inset 0 0 0 1px ${theme.colors.white}`,
  'outlined-secondary-default': `inset 0 0 0 1px ${theme.colors.white}`,
  'outlined-success-default': `inset 0 0 0 1px ${theme.colors.success}`,
  'outlined-danger-default': `inset 0 0 0 1px ${theme.colors.error}`,
  'outlined-primary-hover': `inset 0 0 0 1px ${theme.colors.white}`,
  'outlined-secondary-hover': `inset 0 0 0 1px ${theme.colors.white}`,
  'outlined-success-hover': `inset 0 0 0 1px ${theme.colors.blue500}`,
  'outlined-danger-hover': `inset 0 0 0 1px ${theme.colors.red500}`,
  'outlined-primary-press': `inset 0 0 0 1px ${theme.colors.white}`,
  'outlined-secondary-press': `inset 0 0 0 1px ${theme.colors.white}`,
  'outlined-success-press': `inset 0 0 0 1px ${theme.colors.blue600}`,
  'outlined-danger-press': `inset 0 0 0 1px ${theme.colors.red600}`,
  'text-primary-default': 'none',
  'text-secondary-default': 'none',
  'text-success-default': 'none',
  'text-danger-default': 'none',
  'text-primary-hover': `inset 0 -0.8px 0 0 ${theme.colors.gray50}`,
  'text-secondary-hover': `inset 0 -0.8px 0 0 ${theme.colors.gray50}`,
  'text-success-hover': `inset 0 -0.8px 0 0 ${theme.colors.gray50}`,
  'text-danger-hover': `inset 0 -0.8px 0 0 ${theme.colors.gray50}`,
  'text-primary-press': `inset 0 -0.8px 0 0 ${theme.colors.gray100}`,
  'text-secondary-press': `inset 0 -0.8px 0 0 ${theme.colors.gray100}`,
  'text-success-press': `inset 0 -0.8px 0 0 ${theme.colors.gray100}`,
  'text-danger-press': `inset 0 -0.8px 0 0 ${theme.colors.gray100}`,
  'floating-primary-default': 'none',
  'floating-secondary-default': 'none',
  'floating-success-default': 'none',
  'floating-danger-default': 'none',
  'floating-primary-hover': 'none',
  'floating-secondary-hover': 'none',
  'floating-success-hover': 'none',
  'floating-danger-hover': 'none',
  'floating-primary-press': 'none',
  'floating-secondary-press': 'none',
  'floating-success-press': 'none',
  'floating-danger-press': 'none',
};

export const borderRadiuses: Record<ButtonSizeTheme | 'text' | 'floating', string> = {
  sm: '8px',
  md: '10px',
  lg: '12px',
  text: 'none',
  floating: '18px',
};

export const paddings: Record<ButtonSizeTheme | 'text' | 'floating-default' | 'floating-extended', string> = {
  'sm': '9px 14px',
  'md': '12px 20px',
  'lg': '16px 26px',
  'text': '0 0 4px',
  'floating-default': '10px',
  'floating-extended': '12px 14px',
};

export const fontSizes: Record<ButtonSizeTheme, string> = {
  sm: '14px',
  md: '16px',
  lg: '18px',
};

export const iconSizes: Record<ButtonSizeTheme | 'floating', number> = {
  sm: 16,
  md: 20,
  lg: 24,
  floating: 28,
};
