export * from "./Icon/Communication/index";
export * from "./Icon/Editor/index";
export * from "./Icon/Feedback/index";
export * from "./Icon/Files/index";
export * from "./Icon/General/index";
export * from "./Icon/Interaction/index";
export * from "./Icon/Media/index";
export * from "./Icon/Time/index";
export * from "./Icon/Users/index";
