export * from "./src/Icon/Communication/index";
export * from "./src/Icon/Editor/index";
export * from "./src/Icon/Feedback/index";
export * from "./src/Icon/Files/index";
export * from "./src/Icon/General/index";
export * from "./src/Icon/Interaction/index";
export * from "./src/Icon/Media/index";
export * from "./src/Icon/Time/index";
export * from "./src/Icon/Users/index";
